name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Show npm debug log
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log || true

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier check
        run: npx prettier --check .

      - name: Build application
        run: npm run build

      - name: Run unit tests with coverage
        run: npm run test -- --coverage

      - name: Upload test coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 7

      # The cypress-io/github-action@v6 uses a pre-configured GitHub runner image
      # that already includes these system dependencies, so we can remove this step
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
          browser: chrome
          record: false

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7
