name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Show npm debug log
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log || true
      
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier check
        run: npx prettier --check .

      - name: Run tests
        run: npm run test
